parameters:  
  "service-dir":
    default: "sdk/programmableconnectivity"
  "dependencies":
    "additionalDirectories": []
    default: ""
emit:
  - "@azure-tools/typespec-autorest"
  - "@azure-tools/typespec-python"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emitter-output-dir: "{project-root}/.."
    examples-directory: "{project-root}/examples"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
  "@azure-tools/typespec-python":
    package-mode: "dataplane"
    package-dir: "azure-programmableconnectivity"
    package-name: "{package-dir}"
linter:
  extends:
    - "@azure-tools/typespec-azure-core/all"
